In [1]:
import numpy as np

In [3]:
list = [1,2,3,4]
print(list)

[1, 2, 3, 4]


In [4]:
def add(a,b):
    return(a+b)

In [5]:
a = [1,2,3,4]
b = [2,4,6,7]

In [7]:
add(a,b)

[1, 2, 3, 4, 2, 4, 6, 7]

In [12]:
myVect = np.arange(1, 10, 3)

In [13]:
print(myVect)

[1 4 7]


In [14]:
myVect = np.ones(4, dtype = np.int16)

In [15]:
print(myVect)

[1 1 1 1]


In [21]:
myVect = np.zeros(17, dtype = np.int16)

In [22]:
print(myVect)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [23]:
print(myVect + 1)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [28]:
arr1= np.array([2, 4, 6, 8])

In [29]:
print(arr1 ** 2)

[ 4 16 36 64]


In [30]:
arr2 = arr1.copy()

In [31]:
print(arr2)

[2 4 6 8]


In [32]:
print(arr2 * 2)

[ 4  8 12 16]


In [34]:
print(arr2 ==arr1)

[ True  True  True  True]


In [39]:
print(arr1 * arr2)

[ 4 16 36 64]


In [40]:
arr1.dot(arr2)

120